In [1]:
import numpy as np

# Numpy Basics

In [2]:
array = np.array([1, 2, 3])

In [3]:
array

array([1, 2, 3])

Numpy'da array oluşturma

In [8]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [9]:
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
array.shape

(3, 3)

In [11]:
array.ndim

2

In [12]:
array.size

9

In [13]:
array.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.empty((4,4))

array([[4.67296746e-307, 1.69121096e-306, 4.45062305e-308,
        6.23036978e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [18]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
np.linspace(10,50,20)

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])