In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3])

In [3]:
array2 = np.array([4,5,6])

In [4]:
array + array2

array([5, 7, 9])

In [5]:
array - array2

array([-3, -3, -3])

In [6]:
array * array2

array([ 4, 10, 18])

In [14]:
array = np.array([[1,2,3], [4,5,6]])

In [9]:
array2 = np.array([[10, 15, 20], [25,30,35]])

In [13]:
array.dot(array2)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [15]:
array.shape

(2, 3)

In [16]:
array2.shape

(2, 3)

In [17]:
array2.T

array([[10, 25],
       [15, 30],
       [20, 35]])

In [18]:
array.dot(array2.T)

array([[100, 190],
       [235, 460]])