In [1]:
import numpy as np

In [2]:
a = np.random.random((5,5))

In [4]:
print(a)

[[0.47607868 0.67928354 0.84297572 0.46730579 0.27035449]
 [0.66502789 0.3097827  0.20625605 0.93605659 0.64662592]
 [0.68486865 0.34419245 0.95704096 0.92523345 0.3697086 ]
 [0.21841418 0.80457434 0.63504072 0.4937197  0.27106432]
 [0.2652243  0.3903666  0.76733582 0.78028987 0.32431488]]


In [5]:
a.sum()

13.731136214923719

In [6]:
a.sum(axis=0)

array([2.3096137 , 2.52819964, 3.40864927, 3.6026054 , 1.8820682 ])

In [7]:
a.sum(axis=1)

array([2.73599823, 2.76374915, 3.28104411, 2.42281325, 2.52753147])

In [10]:
print(a < 0.5)

[[ True False False  True  True]
 [False  True  True False False]
 [False  True False False  True]
 [ True False False  True  True]
 [ True  True False False  True]]


In [11]:
np.square(a)

array([[0.22665091, 0.46142613, 0.71060807, 0.2183747 , 0.07309155],
       [0.4422621 , 0.09596532, 0.04254156, 0.87620195, 0.41812507],
       [0.46904507, 0.11846845, 0.9159274 , 0.85605693, 0.13668445],
       [0.04770475, 0.64733987, 0.40327671, 0.24375915, 0.07347586],
       [0.07034393, 0.15238608, 0.58880426, 0.60885228, 0.10518014]])

In [12]:
np.sqrt(a)

array([[0.68998455, 0.8241866 , 0.91813709, 0.68359768, 0.51995624],
       [0.81549242, 0.55658126, 0.45415422, 0.96750018, 0.80413053],
       [0.82756792, 0.58667917, 0.9782847 , 0.96189056, 0.60803667],
       [0.46734802, 0.89698068, 0.79689442, 0.70265191, 0.52063837],
       [0.51499932, 0.62479325, 0.87597706, 0.88334018, 0.56948651]])

In [15]:
b = a.ravel()

In [37]:
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [38]:
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [46]:
b[2] = 55

In [40]:
c = b.reshape(5,3)

In [41]:
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [42]:
c[1,1]

5

In [44]:
c[1:3, 0:2]

array([[4, 5],
       [7, 8]])

3x3'lük bir sıfır matris oluştur.
Kafana göre 3 değeri değiştir.
Hangilerinin 0 olup olmadığını gösteren bir array oluştur.

In [48]:
a = np.zeros((3,3))

In [49]:
a[2,2] = 5

In [50]:
a[0,2] = 6

In [51]:
a[1,0] = 2

In [52]:
a

array([[0., 0., 6.],
       [2., 0., 0.],
       [0., 0., 5.]])

In [54]:
print(a == 0)

[[ True  True False]
 [False  True  True]
 [ True  True False]]


1'den 15'e kadar sayılardan oluşan 5x3'lük bir matris oluştur.
5,6,8,9 olan kısmı gösteren array oluştur.

In [55]:
a = np.arange(1,16)

In [56]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
b = a.reshape(5, 3)

In [59]:
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [62]:
print(b[1:3, 1:3])

[[5 6]
 [8 9]]


In [63]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [64]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
b = a.ravel()

In [67]:
print(b[3])

4


In [73]:
array1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [70]:
array2 = np.array([[-1,-2,-3], [-4,-5,-6], [-7,-8,-9]])

In [74]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
array2

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [75]:
np.vstack((array1, array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [76]:
np.hstack((array1, array2))

array([[ 1,  2,  3, -1, -2, -3],
       [ 4,  5,  6, -4, -5, -6],
       [ 7,  8,  9, -7, -8, -9]])

In [77]:
liste = [1,2,3,4,5,6,7,8,9]

In [78]:
array = np.array(liste)

In [79]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
liste2 = list(array)

In [81]:
liste2

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
array

array([ 1,  2,  3, 55,  5,  6,  7,  8,  9])

In [93]:
array2 = np.copy(array)

In [94]:
array2

array([ 1,  2,  3, 55,  5,  6,  7,  8,  9])

In [95]:
array2[3] = 82

In [96]:
array2

array([ 1,  2,  3, 82,  5,  6,  7,  8,  9])

In [98]:
array

array([ 1,  2,  3, 55,  5,  6,  7,  8,  9])